# Generated as the initial schema for Barangay Connect.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='BarangayProfile', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(default='Barangay Mabuhay', max_length=150)), ('municipality', models.CharField(blank=True, max_length=150)), ('province', models.CharField(blank=True, max_length=150)), ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')), ('captain_name', models.CharField(blank=True, max_length=150)), ('secretary_name', models.CharField(blank=True, max_length=150)), ('address', models.TextField(blank=True)), ('contact_number', models.CharField(blank=True, max_length=30)), ('email', models.EmailField(blank=True, max_length=254))]),
        migrations.CreateModel(name='CertificateTemplate', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('certificate_type', models.CharField(choices=[('clearance','Barangay Clearance'),('residency','Certificate of Residency'),('indigency','Certificate of Indigency'),('good_moral','Certificate of Good Moral'),('business','Business Permit')], max_length=20, unique=True)), ('title', models.CharField(max_length=150)), ('body', models.TextField(help_text='Use {{ resident.full_name }}, {{ request.purpose }}, and {{ barangay.name }}.')), ('footer', models.TextField(blank=True)), ('updated_at', models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='IDTemplate', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(default='Official Barangay ID', max_length=100)), ('header_color', models.CharField(default='#0d6efd', max_length=7)), ('accent_color', models.CharField(default='#ffc107', max_length=7)), ('show_qr', models.BooleanField(default=True)), ('is_active', models.BooleanField(default=True)), ('updated_at', models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Resident', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('resident_no', models.CharField(blank=True, max_length=24, unique=True)), ('first_name', models.CharField(max_length=80)), ('middle_name', models.CharField(blank=True, max_length=80)), ('last_name', models.CharField(max_length=80)), ('birth_date', models.DateField()), ('sex', models.CharField(choices=[('M','Male'),('F','Female'),('O','Other')], max_length=1)), ('civil_status', models.CharField(choices=[('single','Single'),('married','Married'),('widowed','Widowed'),('separated','Separated')], default='single', max_length=12)), ('address', models.TextField()), ('purok', models.CharField(blank=True, max_length=100)), ('contact_number', models.CharField(blank=True, max_length=30)), ('occupation', models.CharField(blank=True, max_length=120)), ('photo', models.ImageField(blank=True, null=True, upload_to='residents/')), ('is_active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Notification', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=150)), ('message', models.TextField()), ('url', models.CharField(blank=True, max_length=300)), ('is_read', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL))], options={'ordering':['-created_at']}),
        migrations.CreateModel(name='ActivityLog', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('action', models.CharField(max_length=150)), ('detail', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={'ordering':['-created_at']}),
        migrations.CreateModel(name='CertificateRequest', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('reference_no', models.CharField(blank=True, max_length=30, unique=True)), ('certificate_type', models.CharField(choices=[('clearance','Barangay Clearance'),('residency','Certificate of Residency'),('indigency','Certificate of Indigency'),('good_moral','Certificate of Good Moral'),('business','Business Permit')], max_length=20)), ('purpose', models.TextField()), ('business_name', models.CharField(blank=True, max_length=150)), ('business_address', models.TextField(blank=True)), ('status', models.CharField(choices=[('pending','Pending'),('reviewing','Under review'),('approved','Approved'),('released','Released'),('rejected','Rejected')], default='pending', max_length=12)), ('remarks', models.TextField(blank=True)), ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)), ('requested_at', models.DateTimeField(auto_now_add=True)), ('reviewed_at', models.DateTimeField(blank=True, null=True)), ('released_at', models.DateTimeField(blank=True, null=True)), ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)), ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='core.resident')), ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL))]),
    ]
